name: Run Python Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: slotbooking_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flask-testing mysql-connector-python
    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          mysqladmin ping -h127.0.0.1 -utestuser -ptestpass && break
          sleep 2
        done
    - name: Create slots table
      run: |
        mysql -h127.0.0.1 -utestuser -ptestpass slotbooking_test < scripts/setup_test_db.sql
    - name: Run tests
      env:
        DB_TEST_HOST: 127.0.0.1
        DB_TEST_USER: testuser
        DB_TEST_PASSWORD: testpass
        DB_TEST_NAME: slotbooking_test
        DB_TEST_PORT: 3306
      run: pytest tests/test_api.py tests/test_db_connection.py
